import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const ServiceCard = ({ title, description }) => (_jsxs("div", { style: {
        width: "355.82px",
        height: "355.82px",
    }, className: "bg-purple-card rounded-[33.81px] p-8 relative", children: [_jsx("div", { className: "w-[96.6px] h-[96.6px] bg-orange-500 rounded-full absolute -top-12 right-8" }), _jsx("h3", { className: "text-white card-title mt-[63px] mb-4", children: title }), _jsx("p", { className: "text-gray-300 card-desc", children: description })] }));
const ServicesTwo = () => {
    return (_jsx("section", { className: "bg-purple-darker py-16 h-[1099px]", children: _jsxs("div", { className: "container mx-auto pt-[153px]", children: [_jsxs("h2", { className: "services-title", children: [_jsx("span", { className: "text-white", children: "Our " }), _jsx("span", { className: "text-orange-500", children: "Services" })] }), _jsx("p", { className: "services-desc-two", children: "Boost Your Brand's Presence With Targeted Social Media Strategies Designed To Engage, Grow, And Convert Audiences Across All Platforms. Let Us Help You Connect Authentically And Drive Impactful Results." }), _jsxs("div", { className: "flex items-center justify-center gap-[46.18px]", children: [_jsx(ServiceCard, { title: "Political Campaigns", description: "In The Fast-Paced World Of Politics, Every Connection Counts. We Help You Create Campaigns That Resonate With Constituents And Drive Voter Engagement." }), _jsx(ServiceCard, { title: "Meta Ads", description: "Maximize Your ROI With Our Expertise In Meta Ads. We Create And Manage Targeted Campaigns That Reach Your Core Audience And Convert Leads Into Loyal Customers." }), _jsx(ServiceCard, { title: "Lead Generation", description: "Turn Potential Customers Into Lifelong Advocates. Our Lead Generation Strategies Are Designed To Attract, Nurture, And Convert Leads Effectively." })] })] }) }));
};
export default ServicesTwo;
