import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const ServiceCard = ({ title, description }) => (_jsxs("div", { style: {
        width: "355.82px",
        height: "355.82px",
    }, className: "bg-purple-card rounded-[33.81px] p-8 relative", children: [_jsx("div", { className: "w-[96.6px] h-[96.6px] bg-orange-500 rounded-full absolute -top-12 right-8" }), _jsx("h3", { className: "text-white card-title mt-[63px] mb-4", children: title }), _jsx("p", { className: "text-gray-300 card-desc", children: description })] }));
const ServicesOne = () => {
    return (_jsx("section", { className: "bg-orange-primary h-[1099px]", children: _jsxs("div", { className: "mx-auto pt-[153px]", children: [_jsxs("div", { className: "h-[360px]", children: [_jsxs("h2", { className: "services-title", children: [_jsx("span", { className: "text-purple-950", children: "Our " }), _jsx("span", { className: "text-purple-950", children: "Services" })] }), _jsx("p", { className: "text-center text-purple-950 max-w-3xl mx-auto mb-16", children: "Boost Your Brand's Presence With Targeted Social Media Strategies Designed To Engage, Grow, And Convert Audiences Across All Platforms. Let Us Help You Connect Authentically And Drive Impactful Results." })] }), _jsxs("div", { className: "flex h-[695px] pb-[144px] items-center bg-purple-primary justify-center gap-[46.18px]", children: [_jsx(ServiceCard, { title: "Brand Identity", description: "Your Brand Is More Than Just A Logo - It's Your Story. We Help You Position Your Brand With Visual Brand Identities That Resonate With Your Audience And Tell Your Story Authentically." }), _jsx(ServiceCard, { title: "Social Media Marketing", description: "Harness The Power Of Social Media To Connect With Your Target Audience. Our Tailored Strategies Drive Traffic And Build Community Around Your Brand." }), _jsx(ServiceCard, { title: "Influencer Marketing", description: "Leverage The Power Of Targeted Creative To Amplify Your Message. We Identify The Right Influencers To Reach Your Target Market And Drive Connections With Your Target Market." })] })] }) }));
};
export default ServicesOne;
